server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
    hostname: 192.168.1.163
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka_url:http://192.168.1.163:8761/eureka/}