eureka:
  instance:
    prefer-ip-address: true
    hostname: 192.168.1.163
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.1.163:8761/eureka/}