FROM eclipse-temurin:17
VOLUME /tmp
COPY target/OrganizationDiscovery-0.0.1-SNAPSHOT.jar /app/OrganizationDiscovery-0.0.1-SNAPSHOT.jar.jar
CMD ["java", "-jar", "/app/OrganizationDiscovery-0.0.1-SNAPSHOT.jar.jar"]