FROM eclipse-temurin:17
VOLUME /tmp
COPY target/service_discovery-0.0.1-SNAPSHOT.jar /app/service_discovery-0.0.1-SNAPSHOT.jar.jar
CMD ["java", "-jar", "/app/service_discovery-0.0.1-SNAPSHOT.jar.jar"]